/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TareImport } from './routes/tare'
import { Route as ReceiptImport } from './routes/receipt'
import { Route as NameImport } from './routes/name'
import { Route as InfoImport } from './routes/info'
import { Route as CloseDoorsImport } from './routes/close-doors'
import { Route as CartImport } from './routes/cart'
import { Route as AdminImport } from './routes/admin'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TareRoute = TareRouteImport.update({
  id: '/tare',
  path: '/tare',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptRoute = ReceiptRouteImport.update({
  id: '/receipt',
  path: '/receipt',
  getParentRoute: () => rootRouteImport,
} as any)
const NameRoute = NameRouteImport.update({
  id: '/name',
  path: '/name',
  getParentRoute: () => rootRoute,
} as any)
const InfoRoute = InfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => rootRouteImport,
} as any)
const CloseDoorsRoute = CloseDoorsRouteImport.update({
  id: '/close-doors',
  path: '/close-doors',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/close-doors': typeof CloseDoorsRoute
  '/info': typeof InfoRoute
  '/inventory': typeof InventoryRoute
  '/name': typeof NameRoute
  '/receipt': typeof ReceiptRoute
  '/tare': typeof TareRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/close-doors': typeof CloseDoorsRoute
  '/info': typeof InfoRoute
  '/inventory': typeof InventoryRoute
  '/name': typeof NameRoute
  '/receipt': typeof ReceiptRoute
  '/tare': typeof TareRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/close-doors': typeof CloseDoorsRoute
  '/info': typeof InfoRoute
  '/inventory': typeof InventoryRoute
  '/name': typeof NameRoute
  '/receipt': typeof ReceiptRoute
  '/tare': typeof TareRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cart'
    | '/close-doors'
    | '/info'
    | '/inventory'
    | '/name'
    | '/receipt'
    | '/tare'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/cart'
    | '/close-doors'
    | '/info'
    | '/inventory'
    | '/name'
    | '/receipt'
    | '/tare'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cart'
    | '/close-doors'
    | '/info'
    | '/inventory'
    | '/name'
    | '/receipt'
    | '/tare'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CartRoute: typeof CartRoute
  CloseDoorsRoute: typeof CloseDoorsRoute
  InfoRoute: typeof InfoRoute
  InventoryRoute: typeof InventoryRoute
  NameRoute: typeof NameRoute
  ReceiptRoute: typeof ReceiptRoute
  TareRoute: typeof TareRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CartRoute: CartRoute,
  CloseDoorsRoute: CloseDoorsRoute,
  InfoRoute: InfoRoute,
  InventoryRoute: InventoryRoute,
  NameRoute: NameRoute,
  ReceiptRoute: ReceiptRoute,
  TareRoute: TareRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
